<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Balances Import</title>
</head>
<body style="margin:0;padding:0;background:#eef3f6;font-family:Arial,Helvetica,sans-serif;color:#1f2937;">
    @php
        $colors = [
            'success' => ['#166534', '#22c55e'],
            'warning' => ['#b45309', '#f59e0b'],
            'error'   => ['#b91c1c', '#ef4444'],
            'info'    => ['#0369a1', '#0082BB'],
        ];
        [$headerColor, $headerColor2] = $colors[$level] ?? $colors['info'];
    @endphp

    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#eef3f6;margin:0;padding:28px 12px;">
        <tr>
            <td align="center">
                <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:640px;background:#ffffff;border-radius:16px;overflow:hidden;border:1px solid #dbe7ee;box-shadow:0 14px 34px rgba(15,23,42,0.10);">
                    <tr>
                        <td style="padding:26px 28px;background:{{ $headerColor }};background-image:linear-gradient(130deg,{{ $headerColor }},{{ $headerColor2 }});color:#ffffff;">
                            <p style="margin:0 0 6px;font-size:11px;font-weight:800;letter-spacing:1.4px;text-transform:uppercase;color:#eef2ff;">
                                BALANCES IMPORT &middot; {{ strtoupper($level) }}
                            </p>
                            <h1 style="margin:0;font-size:22px;line-height:1.25;font-weight:800;color:#ffffff;">
                                {{ $heading }}
                            </h1>
                        </td>
                    </tr>

                    <tr>
                        <td style="padding:24px 28px 8px;">
                            <p style="margin:0 0 16px;font-size:14px;line-height:1.6;color:#111827;">{{ $statusMessage }}</p>

                            @if(!empty($details))
                                <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">
                                    @foreach($details as $key => $value)
                                        <tr>
                                            <td style="padding:8px 0;border-bottom:1px solid #eef1f4;font-size:12px;font-weight:800;text-transform:uppercase;color:#6b7280;width:38%;">{{ $key }}</td>
                                            <td style="padding:8px 0;border-bottom:1px solid #eef1f4;font-size:14px;color:#111827;">{{ $value }}</td>
                                        </tr>
                                    @endforeach
                                </table>
                            @endif
                        </td>
                    </tr>

                    <tr>
                        <td style="padding:18px 28px 26px;">
                            <p style="margin:0;font-size:11px;line-height:1.6;color:#9ca3af;border-top:1px solid #e5e7eb;padding-top:14px;">
                                Auto-generated by the Balances Import scheduler.
                            </p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>
